on:
  push:
    branches:
      - main
      
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './*'
          remote_path: '/srv/satanshycom.2d4f03b3.configr.cloud/www'
          args: '-o ConnectTimeout=5'