on: [push]
jobs:
  - upload:
      - name: Upload build to hosting environment
        uses: Atyn/Simple-SFTP
        with:
          url: sftp://satanshy:!S4t4nshy@ip-45-79-3-179.cloudezapp.io/srv/satanshycom.2d4f03b3.configr.cloud/www
          local-directory: build-output